@startuml

package SHaclEx {
[Schema] as Schema
[ShExSchema] as ShExSchema
[SHACLSchema] as SHACLSchema
[Converter] as Converter
}

package ShEx-s {
[ShEx] as ShEx
'[RBE] as RBE
[ShapeMaps] as shapeMaps
'[DepGraphs] as depGraphs

}

package SHACL-s {
 [SHACL] as SHACL
}

package SRDF {

 [SRDF] as SRDFComponent
 [SRDF4j] as SRDF4j
 [SRDFJena] as SRDFJena

}


note left of SRDFJena
 RDFAsJenaModel
end note

[Apache Jena] as ApacheJena
[RDF4j] as RDF4j

Schema <|-- ShExSchema
Schema <|-- SHACLSchema
ShExSchema --> ShEx
SHACLSchema --> SHACL
Converter --> ShEx
Converter --> SHACL
ShEx --> shapeMaps
'ShEx --> RBE
'ShEx --> depGraphs
SHACL --> SRDFComponent
ShEx --> SRDFComponent


package RDFShapeClient {

} 
package WikiShape {

} 

package RDFShape {

} 

package UMLSHaclEX {

}

package shexJava {

}


shexJava --> Schema
WikiShape --> RDFShape
RDFShape --> UMLSHaclEX
RDFShape --> Schema
UMLSHaclEX --> Schema
RDFShapeClient --> RDFShape

SRDFComponent <|-- SRDFJena
SRDFComponent <|-- SRDF4j
SRDFJena --> ApacheJena
SRDF4j --> RDF4j


note left of RDFShapeClient 
 Online demo deployed at
 <b>http://rdfshape.weso.es<b>
end note
note right of WikiShape 
 Online demo deployed at
 <b>http://wikishape.weso.es</b>
end note


note left of shexJava 
 Demo using
 SHACLex from
 Java
end note





@enduml