addSbtPlugin("com.codecommit"   % "sbt-github-actions"  % "0.14.2")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "1.1.1")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.github.sbt"   % "sbt-unidoc"          % "0.5.0")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"      % "1.5.10")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"             % "1.0.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-site"            % "1.4.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.8.1")
addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.2")
// addSbtPlugin("org.scalameta"     % "sbt-mdoc"            % "2.2.24")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.8.2")

addCompilerPlugin("com.olegpy" %% "better-monadic-for" % "0.3.1")
