addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"          % "0.4.2")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "0.14.10")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.9.0")
// addSbtPlugin("com.typesafe.sbt"  % "sbt-twirl"           % "1.4.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-site"            % "1.4.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-ghpages"         % "0.6.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.4.1")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.9.1")
addSbtPlugin("org.lyranthe.sbt"  % "partial-unification" % "1.1.2")
addSbtPlugin("org.foundweekends" % "sbt-bintray"         % "0.5.5")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.6.0")
addSbtPlugin("com.simplytyped"   % "sbt-antlr4"          % "0.8.2")
